# Generated by Django 3.1.7 on 2021-07-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPeludo', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='celular',
        ),
    ]
